# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yuki Kajura Discography
email: emily.e.serven@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test website for UConnStamford's Digital Media and Design
  web design and development class.
#baseurl: "" # Hide this if pushing to github
baseurl: "/testjekyll" # Hide this if testing on local environment
#url: "localhost" # the base hostname & protocol for your site
url: "http://emilyeserven.github.io" # the base hostname & protocol for your site
twitter_username: emilyeserven
github_username:  emilyeserven

# Build settings
markdown: kramdown
